sudo: false
language: haskell
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - 'cabal-install-1.22'
      - 'ghc-7.6.3'
      - 'ghc-7.8.4'
      - 'ghc-7.10.1'
env:
  global:
    - CABALVERSION='1.22'
  matrix:
    - GHCVERSION='7.6.3'
    - GHCVERSION='7.8.4'
    - GHCVERSION='7.10.1'
before_install:
  - export PATH="/opt/ghc/$GHCVERSION/bin:/opt/cabal/$CABALVERSION/bin:$PATH"
  - ghc --version
  - cabal --version
  - cabal install packdeps      # To check dependencies
  - cabal sandbox init
install:
  - cabal install --enable-tests --only-dependencies
script:
  - packdeps keyring.cabal
  - cabal configure --enable-tests --ghc-options='-Wall -Werror' --flags 'example allbackends'
  - cabal build
  - cabal test
