language: haskell
ghc:
  - 7.6
  - 7.8
install:
  - cabal sandbox init
  - cabal install --enable-tests --only-dependencies
script:
  - cabal configure --enable-tests --ghc-options='-Wall -Werror' --flags 'example allbackends'
  - cabal build
  - cabal test
